# Generated by Django 2.0.10 on 2019-01-05 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0002_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 11, 47, 30, 471644, tzinfo=utc)),
        ),
    ]
