# Generated by Django 2.0.10 on 2019-01-05 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0003_links_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 11, 49, 17, 369582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='links',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 11, 49, 17, 370580, tzinfo=utc)),
        ),
    ]
