# Generated by Django 2.0.10 on 2019-01-05 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0004_auto_20190105_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='links',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 11, 51, 35, 670486, tzinfo=utc)),
        ),
    ]
