# Generated by Django 2.0.10 on 2019-01-05 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0005_auto_20190105_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='links',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 14, 12, 5, 41850, tzinfo=utc)),
        ),
    ]
