# Generated by Django 2.0.10 on 2019-01-05 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0007_auto_20190105_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 14, 40, 3, 550727, tzinfo=utc)),
        ),
    ]
