# Generated by Django 2.0.10 on 2019-01-05 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0008_auto_20190105_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_redirect',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 16, 24, 28, 229483, tzinfo=utc)),
        ),
    ]
