# Generated by Django 2.0.10 on 2019-01-05 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0009_auto_20190105_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 17, 20, 32, 31798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
